project:
  title: "Project Title"
  type: website
  output-dir: docs
  resources: www
  render:
    - "pages/*.qmd"

website:
  title: "Project Title"
  navbar:
    right:
      - icon: github
        href: ''
        target: _blank
  sidebar:
    style: docked
    contents:
      - text: Home
        href: pages/index.qmd

format:
  html:
    theme:
      - default
      - brand
      - www/custom.scss
    toc: true
    toc-location: right
    code-tools: true
    code-copy: true
    code-fold: true
    code-summary: "Show the code"
    page-layout: full
    link-external-newwindow: true
    grid:
      body-width: 1100px
      sidebar-width: 250px
      margin-width: 200px
    include-after-body:
      text: |
        <script src="../www/index.js"></script>

number-sections: false
editor: source
